# Workflow to trigger build and deploy java project with maven

name: java-21-build-and-test 
on: [workflow_dispatch, push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository 
        uses: actions/checkout@v4
      - name: checkout repository 
        run: |
          echo "✅ Checked out branch: ${{ github.ref_name }}"         
      - name: install jdk         
        uses: actions/setup-java@v4    
        with: 
          distribution: 'oracle'
          java-version: '21'
      - name: build and package with maven 
        run: |
          echo "building the project...."
          mvn clean install
          echo "Build and test completed successfully"
          
          
      
      
      
    
  
  
